configure now looks for tclsh

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1456,6 +1456,7 @@ if test "$enable_debug" = "yes" ; then
 	fi
 else 
 	V_CCOPT="$OonS"
+	V_DEFINE="$V_DEFINE -DNDEBUG"
 fi
 
 
@@ -1648,12 +1649,21 @@ TCL_LIB_PLACES=" \
 		"
 
 
+if test "$TCL_VERS" = "8.0" ; then 
+	V_TCL_LIBRARY_FILES="\$(TCL_80_LIBRARY_FILES)"
+else
+	V_TCL_LIBRARY_FILES="\$(TCL_76_LIBRARY_FILES)"
+fi
+
+
+
+
 NS_PACKAGE_tcl_PARTIAL=false
 NS_PACKAGE_tcl_COMPLETE=true
 
 
 echo $ac_n "checking for tcl.h""... $ac_c" 1>&6
-echo "configure:1657: checking for tcl.h" >&5
+echo "configure:1667: checking for tcl.h" >&5
 if test "x$d" = "xno"; then
 	: disable header
 	V_INCLUDE_TCL=FAIL
@@ -1698,7 +1708,7 @@ fi
 
 
 echo $ac_n "checking for libtcl$TCL_VERS""... $ac_c" 1>&6
-echo "configure:1702: checking for libtcl$TCL_VERS" >&5
+echo "configure:1712: checking for libtcl$TCL_VERS" >&5
 if test "x$d" = "xno"; then
 	: disable library
 	V_LIB_TCL=FAIL
@@ -1758,7 +1768,7 @@ fi
 
 
 echo $ac_n "checking for init.tcl""... $ac_c" 1>&6
-echo "configure:1762: checking for init.tcl" >&5
+echo "configure:1772: checking for init.tcl" >&5
 if test "x$d" = "xno"; then
 	: disable header
 	V_LIBRARY_TCL=FAIL
@@ -1790,6 +1800,49 @@ else
 
 		echo "$ac_t""$V_LIBRARY_TCL" 1>&6
 	fi
+fi
+
+
+#
+# check for tclsh
+#
+for ac_prog in tclsh$TCL_VERS tclsh tclsh$TCL_OLD_VERS
+do
+# Extract the first word of "$ac_prog", so it can be a program name with args.
+set dummy $ac_prog; ac_word=$2
+echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
+echo "configure:1815: checking for $ac_word" >&5
+if eval "test \"`echo '$''{'ac_cv_prog_V_TCLSH'+set}'`\" = set"; then
+  echo $ac_n "(cached) $ac_c" 1>&6
+else
+  if test -n "$V_TCLSH"; then
+  ac_cv_prog_V_TCLSH="$V_TCLSH" # Let the user override the test.
+else
+  IFS="${IFS= 	}"; ac_save_ifs="$IFS"; IFS="${IFS}:"
+  for ac_dir in $PATH; do
+    test -z "$ac_dir" && ac_dir=.
+    if test -f $ac_dir/$ac_word; then
+      ac_cv_prog_V_TCLSH="$ac_prog"
+      break
+    fi
+  done
+  IFS="$ac_save_ifs"
+fi
+fi
+V_TCLSH="$ac_cv_prog_V_TCLSH"
+if test -n "$V_TCLSH"; then
+  echo "$ac_t""$V_TCLSH" 1>&6
+else
+  echo "$ac_t""no" 1>&6
+fi
+
+test -n "$V_TCLSH" && break
+done
+test -n "$V_TCLSH" || V_TCLSH="no"
+
+if test x"$V_TCLSH" = xno
+then
+	NS_PACKAGE_tcl_COMPLETE=false
 fi
 
 
@@ -1946,7 +1999,7 @@ NS_PACKAGE_tk_COMPLETE=true
 
 
 echo $ac_n "checking for tk.h""... $ac_c" 1>&6
-echo "configure:1950: checking for tk.h" >&5
+echo "configure:2003: checking for tk.h" >&5
 if test "x$d" = "xno"; then
 	: disable header
 	V_INCLUDE_TK=FAIL
@@ -1991,7 +2044,7 @@ fi
 
 
 echo $ac_n "checking for libtk$TK_VERS""... $ac_c" 1>&6
-echo "configure:1995: checking for libtk$TK_VERS" >&5
+echo "configure:2048: checking for libtk$TK_VERS" >&5
 if test "x$d" = "xno"; then
 	: disable library
 	V_LIB_TK=FAIL
@@ -2051,7 +2104,7 @@ fi
 
 
 echo $ac_n "checking for tk.tcl""... $ac_c" 1>&6
-echo "configure:2055: checking for tk.tcl" >&5
+echo "configure:2108: checking for tk.tcl" >&5
 if test "x$d" = "xno"; then
 	: disable header
 	V_LIBRARY_TK=FAIL
@@ -2126,7 +2179,7 @@ else
 fi
 
 
-OTCL_VERS=1.0a2
+OTCL_VERS=0.96
 OTCL_H_PLACES_D="$d \
 		$d/include"
 OTCL_H_PLACES="../otcl \
@@ -2158,7 +2211,7 @@ NS_PACKAGE_otcl_COMPLETE=true
 
 
 echo $ac_n "checking for otcl.h""... $ac_c" 1>&6
-echo "configure:2162: checking for otcl.h" >&5
+echo "configure:2215: checking for otcl.h" >&5
 if test "x$d" = "xno"; then
 	: disable header
 	V_INCLUDE_OTCL=FAIL
@@ -2203,7 +2256,7 @@ fi
 
 
 echo $ac_n "checking for libotcl$OTCL_VERS""... $ac_c" 1>&6
-echo "configure:2207: checking for libotcl$OTCL_VERS" >&5
+echo "configure:2260: checking for libotcl$OTCL_VERS" >&5
 if test "x$d" = "xno"; then
 	: disable library
 	V_LIB_OTCL=FAIL
@@ -2360,7 +2413,7 @@ NS_PACKAGE_TclCL_COMPLETE=true
 
 
 echo $ac_n "checking for tclcl.h""... $ac_c" 1>&6
-echo "configure:2364: checking for tclcl.h" >&5
+echo "configure:2417: checking for tclcl.h" >&5
 if test "x$d" = "xno"; then
 	: disable header
 	V_INCLUDE_TclCL=FAIL
@@ -2405,7 +2458,7 @@ fi
 
 
 echo $ac_n "checking for libtclcl$TclCL_VERS""... $ac_c" 1>&6
-echo "configure:2409: checking for libtclcl$TclCL_VERS" >&5
+echo "configure:2462: checking for libtclcl$TclCL_VERS" >&5
 if test "x$d" = "xno"; then
 	: disable library
 	V_LIB_TclCL=FAIL
@@ -2465,7 +2518,7 @@ fi
 
 
 echo $ac_n "checking for tcl2c++""... $ac_c" 1>&6
-echo "configure:2469: checking for tcl2c++" >&5
+echo "configure:2522: checking for tcl2c++" >&5
 if test "x$d" = "xno"; then
 	: disable header
 	V_TCL2CPP_DIR=FAIL
@@ -2659,12 +2712,12 @@ xincdirs="\
 echo "checking for X11 header files"
 if test "$x_includes" = NONE ; then
 	cat > conftest.$ac_ext <<EOF
-#line 2663 "configure"
+#line 2716 "configure"
 #include "confdefs.h"
 #include <X11/Intrinsic.h>
 EOF
 ac_try="$ac_cpp conftest.$ac_ext >/dev/null 2>conftest.out"
-{ (eval echo configure:2668: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
+{ (eval echo configure:2721: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
 ac_err=`grep -v '^ *+' conftest.out`
 if test -z "$ac_err"; then
   rm -rf conftest*
@@ -2698,7 +2751,7 @@ fi
 echo "checking for X11 library archive"
 if test "$x_libraries" = NONE ; then
 	echo $ac_n "checking for XOpenDisplay in -lX11""... $ac_c" 1>&6
-echo "configure:2702: checking for XOpenDisplay in -lX11" >&5
+echo "configure:2755: checking for XOpenDisplay in -lX11" >&5
 ac_lib_var=`echo X11'_'XOpenDisplay | sed 'y%./+-%__p_%'`
 if eval "test \"`echo '$''{'ac_cv_lib_$ac_lib_var'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
@@ -2706,7 +2759,7 @@ else
   ac_save_LIBS="$LIBS"
 LIBS="-lX11  $LIBS"
 cat > conftest.$ac_ext <<EOF
-#line 2710 "configure"
+#line 2763 "configure"
 #include "confdefs.h"
 /* Override any gcc2 internal prototype to avoid an error.  */
 /* We use char because int might match the return type of a gcc2
@@ -2717,7 +2770,7 @@ int main() {
 XOpenDisplay()
 ; return 0; }
 EOF
-if { (eval echo configure:2721: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest; then
+if { (eval echo configure:2774: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest; then
   rm -rf conftest*
   eval "ac_cv_lib_$ac_lib_var=yes"
 else
@@ -2757,7 +2810,7 @@ V_LIB_X11=-lX11
 if test -n "$V_SHM" ; then
 	if test -z "$x_libraries" ; then
 		echo $ac_n "checking for XShmAttach in -lXext""... $ac_c" 1>&6
-echo "configure:2761: checking for XShmAttach in -lXext" >&5
+echo "configure:2814: checking for XShmAttach in -lXext" >&5
 ac_lib_var=`echo Xext'_'XShmAttach | sed 'y%./+-%__p_%'`
 if eval "test \"`echo '$''{'ac_cv_lib_$ac_lib_var'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
@@ -2765,7 +2818,7 @@ else
   ac_save_LIBS="$LIBS"
 LIBS="-lXext -lX11 $LIBS"
 cat > conftest.$ac_ext <<EOF
-#line 2769 "configure"
+#line 2822 "configure"
 #include "confdefs.h"
 /* Override any gcc2 internal prototype to avoid an error.  */
 /* We use char because int might match the return type of a gcc2
@@ -2776,7 +2829,7 @@ int main() {
 XShmAttach()
 ; return 0; }
 EOF
-if { (eval echo configure:2780: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest; then
+if { (eval echo configure:2833: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest; then
   rm -rf conftest*
   eval "ac_cv_lib_$ac_lib_var=yes"
 else
@@ -2840,14 +2893,76 @@ TCLDEBUG_PATH="\
 		/usr/src/local/tcl-debug \
 		/usr/src/local/otcl-debug-$TCLDEBUG_VERS \
 		"
+TCLDEBUG_PATH_D="$d \
+		$d/lib \
+		$d/../lib \
+		"
+TCLDEBUG_H_PATH="\
+		$PWD/../tcl-debug/include \
+		$PWD/../tcl-debug-$TCLDEBUG_VERS/include \
+		/usr/contrib/include \
+		/usr/local/include \
+		/usr/include \
+		/usr/src/local/tcl-debug/include \
+		/usr/src/local/otcl-debug-$TCLDEBUG_VERS/include \
+		"
+TCLDEBUG_H_PATH_D="$d \
+		$d/include \
+		$d/../include \
+		"
 
 
 NS_PACKAGE_tcldebug_PARTIAL=false
 NS_PACKAGE_tcldebug_COMPLETE=true
 
 
+echo $ac_n "checking for Dbg.h""... $ac_c" 1>&6
+echo "configure:2921: checking for Dbg.h" >&5
+if test "x$d" = "xno"; then
+	: disable header
+	V_INCLUDE_TCLDEBUG=FAIL
+	NS_PACKAGE_tcldebug_COMPLETE=false
+	echo "$ac_t""no" 1>&6
+
+else
+	places="$TCLDEBUG_H_PATH"
+	if test "x$d" != "x" -a "x$d" != xyes; then
+		if test ! -d $d; then
+			{ echo "configure: error: $d is not a directory" 1>&2; exit 1; }
+		fi
+		places="$TCLDEBUG_H_PATH_D"
+	fi
+
+	V_INCLUDE_TCLDEBUG=""
+	for dir in $places; do
+		if test -r $dir/Dbg.h; then
+			V_INCLUDE_TCLDEBUG="-I$dir"
+			break
+		fi
+	done
+	if test "FAIL$V_INCLUDE_TCLDEBUG" = "FAIL" ; then
+		NS_PACKAGE_tcldebug_COMPLETE=false
+		echo "$ac_t""no" 1>&6
+	else
+
+				  ac_tr_hdr=HAVE_`echo Dbg.h | sed 'y%abcdefghijklmnopqrstuvwxyz./-%ABCDEFGHIJKLMNOPQRSTUVWXYZ___%'`
+		                cat >> confdefs.h <<EOF
+#define $ac_tr_hdr 1
+EOF
+
+
+		V_INCLUDES="$V_INCLUDE_TCLDEBUG $V_INCLUDES"
+		V_DEFINES="-D$ac_tr_hdr $V_DEFINES"
+
+		NS_PACKAGE_tcldebug_PARTIAL=true
+
+		echo "$ac_t""$V_INCLUDE_TCLDEBUG" 1>&6
+	fi
+fi
+
+
 echo $ac_n "checking for libtcldbg""... $ac_c" 1>&6
-echo "configure:2851: checking for libtcldbg" >&5
+echo "configure:2966: checking for libtcldbg" >&5
 if test "x$d" = "xno"; then
 	: disable library
 	V_LIB_TCLDEBUG=FAIL
@@ -2860,7 +2975,7 @@ else
 		if test ! -d $d; then
 			{ echo "configure: error: $d is not a directory" 1>&2; exit 1; }
 		fi
-		places="$d"
+		places="$TCLDEBUG_PATH_D"
 	fi
 
 	V_LIB_TCLDEBUG=""
@@ -2947,7 +3062,7 @@ DMALLOC_PATH="$PWD/../dmalloc \
 
 if test "x$d" = xUNDEF; then
 	echo $ac_n "checking dmalloc""... $ac_c" 1>&6
-echo "configure:2951: checking dmalloc" >&5
+echo "configure:3066: checking dmalloc" >&5
 	echo "$ac_t""not requested with --with-dmalloc" 1>&6
 else
 	
@@ -2956,7 +3071,7 @@ NS_PACKAGE_dmalloc_COMPLETE=true
 
 	
 echo $ac_n "checking for libdmalloc""... $ac_c" 1>&6
-echo "configure:2960: checking for libdmalloc" >&5
+echo "configure:3075: checking for libdmalloc" >&5
 if test "x$d" = "xno"; then
 	: disable library
 	dmalloc=FAIL
@@ -3016,7 +3131,7 @@ fi
 
 	
 echo $ac_n "checking for dmalloc.h""... $ac_c" 1>&6
-echo "configure:3020: checking for dmalloc.h" >&5
+echo "configure:3135: checking for dmalloc.h" >&5
 if test "x$d" = "xno"; then
 	: disable header
 	dmalloc=FAIL
@@ -3061,7 +3176,7 @@ fi
 
 	
 echo $ac_n "checking for return.h""... $ac_c" 1>&6
-echo "configure:3065: checking for return.h" >&5
+echo "configure:3180: checking for return.h" >&5
 if test "x$d" = "xno"; then
 	: disable header
 	dmalloc=FAIL
@@ -3150,7 +3265,7 @@ PERL_OPTIONAL=${PERL_OPTIONAL:-false}
 
 
 echo $ac_n "checking for perl""... $ac_c" 1>&6
-echo "configure:3154: checking for perl" >&5
+echo "configure:3269: checking for perl" >&5
 if test "x$d" = "xno"; then
 	: disable header
 	PERL=FAIL
@@ -3204,7 +3319,7 @@ if test "x$PERL" = "x"
 then
     
 echo $ac_n "checking for perl5""... $ac_c" 1>&6
-echo "configure:3208: checking for perl5" >&5
+echo "configure:3323: checking for perl5" >&5
 if test "x$d" = "xno"; then
 	: disable header
 	PERL=FAIL
@@ -3337,7 +3452,7 @@ if test ! -z "$V_NEED_DL" ; then
 		;;
 	*-*-linux*)
 		echo $ac_n "checking for dlopen in -ldl""... $ac_c" 1>&6
-echo "configure:3341: checking for dlopen in -ldl" >&5
+echo "configure:3456: checking for dlopen in -ldl" >&5
 ac_lib_var=`echo dl'_'dlopen | sed 'y%./+-%__p_%'`
 if eval "test \"`echo '$''{'ac_cv_lib_$ac_lib_var'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
@@ -3345,7 +3460,7 @@ else
   ac_save_LIBS="$LIBS"
 LIBS="-ldl  $LIBS"
 cat > conftest.$ac_ext <<EOF
-#line 3349 "configure"
+#line 3464 "configure"
 #include "confdefs.h"
 /* Override any gcc2 internal prototype to avoid an error.  */
 /* We use char because int might match the return type of a gcc2
@@ -3356,7 +3471,7 @@ int main() {
 dlopen()
 ; return 0; }
 EOF
-if { (eval echo configure:3360: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest; then
+if { (eval echo configure:3475: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest; then
   rm -rf conftest*
   eval "ac_cv_lib_$ac_lib_var=yes"
 else
@@ -3385,7 +3500,7 @@ fi
 			;;
 		*)
 			echo $ac_n "checking for main in -l$V_LIB_DL""... $ac_c" 1>&6
-echo "configure:3389: checking for main in -l$V_LIB_DL" >&5
+echo "configure:3504: checking for main in -l$V_LIB_DL" >&5
 ac_lib_var=`echo $V_LIB_DL'_'main | sed 'y%./+-%__p_%'`
 if eval "test \"`echo '$''{'ac_cv_lib_$ac_lib_var'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
@@ -3393,14 +3508,14 @@ else
   ac_save_LIBS="$LIBS"
 LIBS="-l$V_LIB_DL $V_STATIC $LIBS"
 cat > conftest.$ac_ext <<EOF
-#line 3397 "configure"
+#line 3512 "configure"
 #include "confdefs.h"
 
 int main() {
 main()
 ; return 0; }
 EOF
-if { (eval echo configure:3404: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest; then
+if { (eval echo configure:3519: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest; then
   rm -rf conftest*
   eval "ac_cv_lib_$ac_lib_var=yes"
 else
@@ -3502,7 +3617,7 @@ V_TAR_TARGET=$target_os
 # SVR4 /usr/ucb/install, which tries to use the nonexistent group "staff"
 # ./install, which can be erroneously created by make from ./install.sh.
 echo $ac_n "checking for a BSD compatible install""... $ac_c" 1>&6
-echo "configure:3506: checking for a BSD compatible install" >&5
+echo "configure:3621: checking for a BSD compatible install" >&5
 if test -z "$INSTALL"; then
 if eval "test \"`echo '$''{'ac_cv_path_install'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
@@ -3713,6 +3828,8 @@ s%@build_os@%$build_os%g
 s%@CC@%$CC%g
 s%@CXX@%$CXX%g
 s%@CPP@%$CPP%g
+s%@V_TCL_LIBRARY_FILES@%$V_TCL_LIBRARY_FILES%g
+s%@V_TCLSH@%$V_TCLSH%g
 s%@V_LIBRARY_TCL@%$V_LIBRARY_TCL%g
 s%@V_TKDOSNAMES@%$V_TKDOSNAMES%g
 s%@V_LIBRARY_TK@%$V_LIBRARY_TK%g
