Now it should be possible to use tcldebug v1.9.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2212,6 +2212,15 @@ else
 	V_NEED_DL=YES
 fi
 
+#if test -r $V_LIBRARY_TK/tkfbox.tcl ; then
+#	echo copied tkfbox.tcl into tcl/
+#	cp $V_LIBRARY_TK/tkfbox.tcl tcl/tkfbox.tcl
+#	chmod +w tcl/tkfbox.tcl
+#else 
+#	echo ABORT: tkfbox.tcl not found! Please check your tk installation.
+#	exit 1
+#fi
+
 
 
 
@@ -2262,7 +2271,7 @@ NS_PACKAGE_otcl_COMPLETE=true
 
 
 echo $ac_n "checking for otcl.h""... $ac_c" 1>&6
-echo "configure:2266: checking for otcl.h" >&5
+echo "configure:2275: checking for otcl.h" >&5
 if test "x$d" = "xno"; then
 	: disable header
 	V_INCLUDE_OTCL=FAIL
@@ -2311,7 +2320,7 @@ fi
 
 
 echo $ac_n "checking for libotcl$OTCL_VERS""... $ac_c" 1>&6
-echo "configure:2315: checking for libotcl$OTCL_VERS" >&5
+echo "configure:2324: checking for libotcl$OTCL_VERS" >&5
 if test "x$d" = "xno"; then
 	: disable library
 	V_LIB_OTCL=FAIL
@@ -2473,7 +2482,7 @@ NS_PACKAGE_TclCL_COMPLETE=true
 
 
 echo $ac_n "checking for tclcl.h""... $ac_c" 1>&6
-echo "configure:2477: checking for tclcl.h" >&5
+echo "configure:2486: checking for tclcl.h" >&5
 if test "x$d" = "xno"; then
 	: disable header
 	V_INCLUDE_TclCL=FAIL
@@ -2522,7 +2531,7 @@ fi
 
 
 echo $ac_n "checking for libtclcl$TclCL_VERS""... $ac_c" 1>&6
-echo "configure:2526: checking for libtclcl$TclCL_VERS" >&5
+echo "configure:2535: checking for libtclcl$TclCL_VERS" >&5
 if test "x$d" = "xno"; then
 	: disable library
 	V_LIB_TclCL=FAIL
@@ -2587,7 +2596,7 @@ fi
 
 
 echo $ac_n "checking for tcl2c++""... $ac_c" 1>&6
-echo "configure:2591: checking for tcl2c++" >&5
+echo "configure:2600: checking for tcl2c++" >&5
 if test "x$d" = "xno"; then
 	: disable header
 	V_TCL2CPP_DIR=FAIL
@@ -2788,12 +2797,12 @@ xincdirs="\
 echo "checking for X11 header files"
 if test "$x_includes" = NONE ; then
 	cat > conftest.$ac_ext <<EOF
-#line 2792 "configure"
+#line 2801 "configure"
 #include "confdefs.h"
 #include <X11/Intrinsic.h>
 EOF
 ac_try="$ac_cpp conftest.$ac_ext >/dev/null 2>conftest.out"
-{ (eval echo configure:2797: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
+{ (eval echo configure:2806: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
 ac_err=`grep -v '^ *+' conftest.out`
 if test -z "$ac_err"; then
   rm -rf conftest*
@@ -2827,7 +2836,7 @@ fi
 echo "checking for X11 library archive"
 if test "$x_libraries" = NONE ; then
 	echo $ac_n "checking for XOpenDisplay in -lX11""... $ac_c" 1>&6
-echo "configure:2831: checking for XOpenDisplay in -lX11" >&5
+echo "configure:2840: checking for XOpenDisplay in -lX11" >&5
 ac_lib_var=`echo X11'_'XOpenDisplay | sed 'y%./+-%__p_%'`
 if eval "test \"`echo '$''{'ac_cv_lib_$ac_lib_var'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
@@ -2835,7 +2844,7 @@ else
   ac_save_LIBS="$LIBS"
 LIBS="-lX11  $LIBS"
 cat > conftest.$ac_ext <<EOF
-#line 2839 "configure"
+#line 2848 "configure"
 #include "confdefs.h"
 /* Override any gcc2 internal prototype to avoid an error.  */
 /* We use char because int might match the return type of a gcc2
@@ -2846,7 +2855,7 @@ int main() {
 XOpenDisplay()
 ; return 0; }
 EOF
-if { (eval echo configure:2850: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest; then
+if { (eval echo configure:2859: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest; then
   rm -rf conftest*
   eval "ac_cv_lib_$ac_lib_var=yes"
 else
@@ -2886,7 +2895,7 @@ V_LIB_X11=-lX11
 if test -n "$V_SHM" ; then
 	if test -z "$x_libraries" ; then
 		echo $ac_n "checking for XShmAttach in -lXext""... $ac_c" 1>&6
-echo "configure:2890: checking for XShmAttach in -lXext" >&5
+echo "configure:2899: checking for XShmAttach in -lXext" >&5
 ac_lib_var=`echo Xext'_'XShmAttach | sed 'y%./+-%__p_%'`
 if eval "test \"`echo '$''{'ac_cv_lib_$ac_lib_var'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
@@ -2894,7 +2903,7 @@ else
   ac_save_LIBS="$LIBS"
 LIBS="-lXext -lX11 $LIBS"
 cat > conftest.$ac_ext <<EOF
-#line 2898 "configure"
+#line 2907 "configure"
 #include "confdefs.h"
 /* Override any gcc2 internal prototype to avoid an error.  */
 /* We use char because int might match the return type of a gcc2
@@ -2905,7 +2914,7 @@ int main() {
 XShmAttach()
 ; return 0; }
 EOF
-if { (eval echo configure:2909: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest; then
+if { (eval echo configure:2918: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest; then
   rm -rf conftest*
   eval "ac_cv_lib_$ac_lib_var=yes"
 else
@@ -2959,32 +2968,26 @@ else
 fi
 
 
-TCLDEBUG_VERS=1.7
+#xxx: Don't know anything about 1.8
+TCLDEBUG_VERS="1.9 1.8 1.7"
+pwd_vers=""
+local_vers=""
+for vers in $TCLDEBUG_VERS; do
+	 pwd_vers="$pwd_vers $PWD/../tcl-debug-$vers"
+	 local_vers="$local_vers /usr/src/local/otcl-debug-$vers"
+done
 TCLDEBUG_PATH="\
 		$PWD/../tcl-debug \
-		$PWD/../tcl-debug-$TCLDEBUG_VERS \
+		$pwd_vers
 		/usr/contrib/lib \
 		/usr/local/lib \
 		/usr/lib \
 		/usr/src/local/tcl-debug \
-		/usr/src/local/otcl-debug-$TCLDEBUG_VERS \
+		$local_vers \
 		"
 TCLDEBUG_PATH_D="$d \
 		$d/lib \
 		$d/../lib \
-		"
-TCLDEBUG_H_PATH="\
-		$PWD/../tcl-debug/include \
-		$PWD/../tcl-debug-$TCLDEBUG_VERS/include \
-		/usr/contrib/include \
-		/usr/local/include \
-		/usr/include \
-		/usr/src/local/tcl-debug/include \
-		/usr/src/local/otcl-debug-$TCLDEBUG_VERS/include \
-		"
-TCLDEBUG_H_PATH_D="$d \
-		$d/include \
-		$d/../include \
 		"
 
 
@@ -2992,57 +2995,9 @@ NS_PACKAGE_tcldebug_UNDERWAY=false
 NS_PACKAGE_tcldebug_COMPLETE=true
 
 
-echo $ac_n "checking for Dbg.h""... $ac_c" 1>&6
-echo "configure:2997: checking for Dbg.h" >&5
-if test "x$d" = "xno"; then
-	: disable header
-	V_INCLUDE_TCLDEBUG=FAIL
-	
-NS_PACKAGE_tcldebug_COMPLETE=false
-
-	echo "$ac_t""no" 1>&6
-
-else
-	places="$TCLDEBUG_H_PATH"
-	if test "x$d" != "x" -a "x$d" != xyes; then
-		if test ! -d $d; then
-			{ echo "configure: error: $d is not a directory" 1>&2; exit 1; }
-		fi
-		places="$TCLDEBUG_H_PATH_D"
-	fi
-
-	V_INCLUDE_TCLDEBUG=""
-	for dir in $places; do
-		if test -r $dir/Dbg.h; then
-			V_INCLUDE_TCLDEBUG="-I$dir"
-			break
-		fi
-	done
-	if test "FAIL$V_INCLUDE_TCLDEBUG" = "FAIL" ; then
-		
-NS_PACKAGE_tcldebug_COMPLETE=false
-
-		echo "$ac_t""no" 1>&6
-	else
-
-				  ac_tr_hdr=HAVE_`echo Dbg.h | sed 'y%abcdefghijklmnopqrstuvwxyz./-%ABCDEFGHIJKLMNOPQRSTUVWXYZ___%'`
-		                cat >> confdefs.h <<EOF
-#define $ac_tr_hdr 1
-EOF
-
-
-		V_INCLUDES="$V_INCLUDE_TCLDEBUG $V_INCLUDES"
-		V_DEFINES="-D$ac_tr_hdr $V_DEFINES"
-
-		NS_PACKAGE_tcldebug_UNDERWAY=true
-
-		echo "$ac_t""$V_INCLUDE_TCLDEBUG" 1>&6
-	fi
-fi
-
 
 echo $ac_n "checking for libtcldbg""... $ac_c" 1>&6
-echo "configure:3046: checking for libtcldbg" >&5
+echo "configure:3001: checking for libtcldbg" >&5
 if test "x$d" = "xno"; then
 	: disable library
 	V_LIB_TCLDEBUG=FAIL
@@ -3105,6 +3060,28 @@ EOF
 	fi
 fi
 
+#if $NS_PACKAGE_tcldebug_COMPLETE; then
+	# look for debugger entry point function
+	#tmpLIBS=$LIBS
+	#LIBS="$V_LIB_TCL $V_LIB_TCLDEBUG"
+
+	# the following two may be needed for linking during tcldbg CHECK_LIB
+	#AC_CHECK_LIB(m, main)
+        #AC_CHECK_LIB(dl, dlopen)
+
+	#notfound=false
+	#AC_CHECK_LIB(tcldbg, Dbg_Init, V_DEFINES="-DHAVE_Dbg_Init $V_DEFINES",notfound=true)
+	#if $notfound; then
+	#	notfound=false
+	#	AC_CHECK_LIB(tcldbg, Tcldbg_Init, V_DEFINES="-DHAVE_Tcldbg_Init $V_DEFINES",notfound=true)
+	#fi
+	#LIBS=$tmpLIBS
+	#if $notfound; then
+	#	echo "configure: warning: Tcl debugger init point is not found.  You \
+#will not be able to use Tcl debugger." 1>&2
+	#	NS_PACKAGE_tcldebug_COMPLETE=false
+	#fi
+#fi
 
 if $NS_PACKAGE_tcldebug_COMPLETE; then
 	
@@ -3153,7 +3130,7 @@ DMALLOC_PATH_D="$d $d/lib $d/include"
 
 if test "x$d" = xUNDEF; then
 	echo $ac_n "checking dmalloc""... $ac_c" 1>&6
-echo "configure:3157: checking dmalloc" >&5
+echo "configure:3134: checking dmalloc" >&5
 	echo "$ac_t""not requested with --with-dmalloc" 1>&6
 else
 	
@@ -3162,7 +3139,7 @@ NS_PACKAGE_dmalloc_COMPLETE=true
 
 	
 echo $ac_n "checking for libdmalloc""... $ac_c" 1>&6
-echo "configure:3166: checking for libdmalloc" >&5
+echo "configure:3143: checking for libdmalloc" >&5
 if test "x$d" = "xno"; then
 	: disable library
 	V_LIB_DMALLOC=FAIL
@@ -3227,7 +3204,7 @@ fi
 
 	
 echo $ac_n "checking for dmalloc.h""... $ac_c" 1>&6
-echo "configure:3231: checking for dmalloc.h" >&5
+echo "configure:3208: checking for dmalloc.h" >&5
 if test "x$d" = "xno"; then
 	: disable header
 	V_HEADER_DMALLOC=FAIL
@@ -3276,7 +3253,7 @@ fi
 
 	
 echo $ac_n "checking for return.h""... $ac_c" 1>&6
-echo "configure:3280: checking for return.h" >&5
+echo "configure:3257: checking for return.h" >&5
 if test "x$d" = "xno"; then
 	: disable header
 	V_HEADER_RETURN=FAIL
@@ -3395,7 +3372,7 @@ PERL_OPTIONAL=${PERL_OPTIONAL:-false}
 
 
 echo $ac_n "checking for perl""... $ac_c" 1>&6
-echo "configure:3399: checking for perl" >&5
+echo "configure:3376: checking for perl" >&5
 if test "x$d" = "xno"; then
 	: disable header
 	PERL=FAIL
@@ -3453,7 +3430,7 @@ if test "x$PERL" = "x"
 then
     
 echo $ac_n "checking for perl5""... $ac_c" 1>&6
-echo "configure:3457: checking for perl5" >&5
+echo "configure:3434: checking for perl5" >&5
 if test "x$d" = "xno"; then
 	: disable header
 	PERL=FAIL
@@ -3543,12 +3520,12 @@ fi
 for ac_func in getrusage sbrk
 do
 echo $ac_n "checking for $ac_func""... $ac_c" 1>&6
-echo "configure:3547: checking for $ac_func" >&5
+echo "configure:3524: checking for $ac_func" >&5
 if eval "test \"`echo '$''{'ac_cv_func_$ac_func'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 3552 "configure"
+#line 3529 "configure"
 #include "confdefs.h"
 /* System header to define __stub macros and hopefully few prototypes,
     which can conflict with char $ac_func(); below.  */
@@ -3571,7 +3548,7 @@ $ac_func();
 
 ; return 0; }
 EOF
-if { (eval echo configure:3575: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest; then
+if { (eval echo configure:3552: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest; then
   rm -rf conftest*
   eval "ac_cv_func_$ac_func=yes"
 else
@@ -3639,7 +3616,7 @@ if test ! -z "$V_NEED_DL" ; then
 		;;
 	*-*-linux*)
 		echo $ac_n "checking for dlopen in -ldl""... $ac_c" 1>&6
-echo "configure:3643: checking for dlopen in -ldl" >&5
+echo "configure:3620: checking for dlopen in -ldl" >&5
 ac_lib_var=`echo dl'_'dlopen | sed 'y%./+-%__p_%'`
 if eval "test \"`echo '$''{'ac_cv_lib_$ac_lib_var'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
@@ -3647,7 +3624,7 @@ else
   ac_save_LIBS="$LIBS"
 LIBS="-ldl  $LIBS"
 cat > conftest.$ac_ext <<EOF
-#line 3651 "configure"
+#line 3628 "configure"
 #include "confdefs.h"
 /* Override any gcc2 internal prototype to avoid an error.  */
 /* We use char because int might match the return type of a gcc2
@@ -3658,7 +3635,7 @@ int main() {
 dlopen()
 ; return 0; }
 EOF
-if { (eval echo configure:3662: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest; then
+if { (eval echo configure:3639: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest; then
   rm -rf conftest*
   eval "ac_cv_lib_$ac_lib_var=yes"
 else
@@ -3687,7 +3664,7 @@ fi
 			;;
 		*)
 			echo $ac_n "checking for main in -l$V_LIB_DL""... $ac_c" 1>&6
-echo "configure:3691: checking for main in -l$V_LIB_DL" >&5
+echo "configure:3668: checking for main in -l$V_LIB_DL" >&5
 ac_lib_var=`echo $V_LIB_DL'_'main | sed 'y%./+-%__p_%'`
 if eval "test \"`echo '$''{'ac_cv_lib_$ac_lib_var'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
@@ -3695,14 +3672,14 @@ else
   ac_save_LIBS="$LIBS"
 LIBS="-l$V_LIB_DL $V_STATIC $LIBS"
 cat > conftest.$ac_ext <<EOF
-#line 3699 "configure"
+#line 3676 "configure"
 #include "confdefs.h"
 
 int main() {
 main()
 ; return 0; }
 EOF
-if { (eval echo configure:3706: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest; then
+if { (eval echo configure:3683: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest; then
   rm -rf conftest*
   eval "ac_cv_lib_$ac_lib_var=yes"
 else
@@ -3811,7 +3788,7 @@ V_TAR_TARGET=$target_os
 # SVR4 /usr/ucb/install, which tries to use the nonexistent group "staff"
 # ./install, which can be erroneously created by make from ./install.sh.
 echo $ac_n "checking for a BSD compatible install""... $ac_c" 1>&6
-echo "configure:3815: checking for a BSD compatible install" >&5
+echo "configure:3792: checking for a BSD compatible install" >&5
 if test -z "$INSTALL"; then
 if eval "test \"`echo '$''{'ac_cv_path_install'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
