configure.in.Tcl revised

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2090,205 +2090,220 @@ else
 fi
 
 
+LIBTCL_VERS=1.0b2
+LIBTCL_ALT_VERS=1.0
 
-LIBTCL_OLD_VERSION=1.0
-LIBTCL_VERSION=1.0b2
-
-if test "$d" != "" ; then 
-	if test ! -d $d ; then 
-		{ echo "configure: error: $d is not a directory" 1>&2; exit 1; }
-	fi
-	V_INCLUDE_BTCL=FAIL
-	echo $ac_n "checking for Tcl.h""... $ac_c" 1>&6
-echo "configure:2104: checking for Tcl.h" >&5
-        places="$d \
-                $d/include"
-        for f in $places; do
-                if test -r $f/Tcl.h ; then
-                        V_INCLUDE_BTCL=-I$f
-                        break   
-                fi      
-        done    
-	echo "$ac_t""$V_INCLUDE_BTCL" 1>&6
-        if test "$V_INCLUDE_BTCL" = FAIL; then
-		{ echo "configure: error: cannot find Tcl.h" 1>&2; exit 1; }
-        fi
-
-	echo $ac_n "checking for libTcl""... $ac_c" 1>&6
-echo "configure:2119: checking for libTcl" >&5
-        places="$d \
-                $d/lib"  
-	V_LIB_BTCL=FAIL
-	for dir in $places; do
-		if test -r $dir/libTcl.so -o -r $dir/libTcl.a ; then
-			V_LIB_BTCL="-L$dir -lTcl"
-			break
-		fi
-	done
-	echo "$ac_t""$V_LIB_BTCL" 1>&6
-	if test "$V_LIB_BTCL" = FAIL ; then
-		{ echo "configure: error: cannot find libTcl" 1>&2; exit 1; }
-	fi
-
-	echo $ac_n "checking for tcl2c++""... $ac_c" 1>&6
-echo "configure:2135: checking for tcl2c++" >&5
-	places="$d \
-		"
-	V_TCL2CPP=FAIL
-	for dir in $places; do
-		if test -r $dir/tcl2c++ ; then
-			V_TCL2CPP=$dir/tcl2c++
-			break
-		fi
-	done
-	echo "$ac_t""$V_TCL2CPP" 1>&6
-	if test "$V_TCL2CPP" = FAIL ; then
-		{ echo "configure: error: cannot find tcl2c++" 1>&2; exit 1; }
-	fi
-else
-	V_INCLUDE_BTCL=FAIL
-	echo $ac_n "checking for Tcl.h""... $ac_c" 1>&6
-echo "configure:2152: checking for Tcl.h" >&5
-        places="../Tcl \
+LIBTCL_H_PLACES="\
+		$PWD/../Tcl-$LIBTCL_VERS \
+		$PWD/../Tcl-$LIBTCL_ALT_VERS \
+		$PWD/../Tcl \
                 /usr/src/local/Tcl \
-                ../$LIBTCL_OLD_VERSION \
-                ../$LIBTCL_VERSION \
+                /usr/src/local/Tcl-1.0 \
                 /import/Tcl/include \
-                /usr/src/local/$LIBTCL_OLD_VERSION \
-                /usr/src/local/$LIBTCL_VERSION \
-                $prefix/include \
                 /usr/local/include \
                 /usr/contrib/include \
                 /usr/include"
-        for dir in $places; do
-                if test -r $dir/Tcl.h ; then
-                        V_INCLUDE_BTCL=-I$dir
-                        break
-                fi
-        done
-	if test "$V_INCLUDE_BTCL" = FAIL; then
-		cat > conftest.$ac_ext <<EOF
-#line 2172 "configure"
-#include "confdefs.h"
-#include <Tcl.h>
-EOF
-ac_try="$ac_cpp conftest.$ac_ext >/dev/null 2>conftest.out"
-{ (eval echo configure:2177: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
-ac_err=`grep -v '^ *+' conftest.out`
-if test -z "$ac_err"; then
-  rm -rf conftest*
-  V_INCLUDE_BTCL=""
-else
-  echo "$ac_err" >&5
-  echo "configure: failed program was:" >&5
-  cat conftest.$ac_ext >&5
-  rm -rf conftest*
-  V_INCLUDE_BTCL=FAIL
-fi
-rm -f conftest*
-	fi
-	echo "$ac_t""$V_INCLUDE_BTCL" 1>&6
-	if test "$V_INCLUDE_BTCL" = FAIL; then
-		{ echo "configure: error: cannot find Tcl.h" 1>&2; exit 1; }
-	fi
-
-	V_LIB_BTCL=FAIL
-	echo $ac_n "checking for libTcl""... $ac_c" 1>&6
-echo "configure:2198: checking for libTcl" >&5
-        places="../Tcl \
-                ../$LIBTCL_OLD_VERSION \
-                ../$LIBTCL_VERSION \
-                $prefix/lib \
+LIBTCL_H_PLACES_D="$d \
+ 		$d/include"
+LIBTCL_LIB_PLACES="\
+		$PWD/../Tcl-$LIBTCL_VERS \
+		$PWD/../Tcl-$LIBTCL_ALT_VERS \
+		$PWD/../Tcl \
                 $x_libraries \
                 /usr/contrib/lib \
                 /usr/local/lib \
                 /usr/lib \
                 /usr/src/local/Tcl \
-                /usr/src/local/$LIBTCL_OLD_VERSION \
-                /usr/src/local/$LIBTCL_VERSION \
-		"
-        for dir in $places; do
-                if test -r $dir/libTcl.so -o -r $dir/libTcl.a; then
-                        V_LIB_BTCL="-L$dir -lTcl"
-                        break
-                fi
-        done    
-        if test "$V_LIB_BTCL" = FAIL; then
-		echo $ac_n "checking for main in -lTcl""... $ac_c" 1>&6
-echo "configure:2219: checking for main in -lTcl" >&5
-ac_lib_var=`echo Tcl'_'main | sed 'y%./+-%__p_%'`
-if eval "test \"`echo '$''{'ac_cv_lib_$ac_lib_var'+set}'`\" = set"; then
-  echo $ac_n "(cached) $ac_c" 1>&6
-else
-  ac_save_LIBS="$LIBS"
-LIBS="-lTcl  $LIBS"
-cat > conftest.$ac_ext <<EOF
-#line 2227 "configure"
-#include "confdefs.h"
-
-int main() {
-main()
-; return 0; }
-EOF
-if { (eval echo configure:2234: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest; then
-  rm -rf conftest*
-  eval "ac_cv_lib_$ac_lib_var=yes"
-else
-  echo "configure: failed program was:" >&5
-  cat conftest.$ac_ext >&5
-  rm -rf conftest*
-  eval "ac_cv_lib_$ac_lib_var=no"
-fi
-rm -f conftest*
-LIBS="$ac_save_LIBS"
-
-fi
-if eval "test \"`echo '$ac_cv_lib_'$ac_lib_var`\" = yes"; then
-  echo "$ac_t""yes" 1>&6
-  V_LIB_BTCL="-lTcl"
-else
-  echo "$ac_t""no" 1>&6
-V_LIB_BTCL="FAIL"
-fi
-
-        fi
-	echo "$ac_t""$V_LIB_BTCL" 1>&6
-        if test "$V_LIB_BTCL" = FAIL; then
-		{ echo "configure: error: cannot find libTcl" 1>&2; exit 1; }
-	fi
-	if test $solaris ; then
-		V_LIB_BTCL="-R$dir $V_LIB_BTCL"
-	fi
-
-	echo $ac_n "checking for tcl2c++""... $ac_c" 1>&6
-echo "configure:2265: checking for tcl2c++" >&5
-	V_TCL2CPP=FAIL
-        places="\
-                ../Tcl \
-                ../$LIBTCL_OLD_VERSION \
-                ../$LIBTCL_VERSION \
+                /usr/src/local/Tcl-1.0"
+LIBTCL_LIB_PLACES_D="$d \
+        $d/lib"  
+LIBTCL_PROG_PLACES="\
+		$PWD/../Tcl-$LIBTCL_VERS \
+		$PWD/../Tcl-$LIBTCL_ALT_VERS \
+		$PWD/../Tcl \
                 $prefix/bin \
                 $x_libraries \
                 /usr/contrib/bin \
                 /usr/local/bin \
                 /usr/bin \
                 /usr/src/local/Tcl \
-                /usr/src/local/$LIBTCL_OLD_VERSION \
-                /usr/src/local/$LIBTCL_VERSION \
-                "       
+                /usr/src/local/Tcl-1.0 \
+                "
+LIBTCL_PROG_PLACES_D="$d"
 
+
+
+NS_PACKAGE_libTcl_PARTIAL=false
+NS_PACKAGE_libTcl_COMPLETE=true
+
+
+echo $ac_n "checking for Tcl.h""... $ac_c" 1>&6
+echo "configure:2142: checking for Tcl.h" >&5
+if test "x$d" = "xno"; then
+	: disable header
+	V_INCLUDE_LIBTCL=FAIL
+	NS_PACKAGE_libTcl_COMPLETE=false
+	echo "$ac_t""no" 1>&6
+
+else
+	places="$LIBTCL_H_PLACES"
+	if test "x$d" != "x" -a "x$d" != xyes; then
+		if test ! -d $d; then
+			{ echo "configure: error: $d is not a directory" 1>&2; exit 1; }
+		fi
+		places="$LIBTCL_H_PLACES_D"
+	fi
+
+	V_INCLUDE_LIBTCL=""
 	for dir in $places; do
-		if test -x $dir/tcl2c++; then
-			V_TCL2CPP=$dir/tcl2c++
+		if test -r $dir/Tcl.h; then
+			V_INCLUDE_LIBTCL="-I$dir"
 			break
 		fi
 	done
-	echo "$ac_t""$V_TCL2CPP" 1>&6
-	if test "$V_TCL2CPP" = FAIL; then
-		{ echo "configure: error: cannot find tcl2c++" 1>&2; exit 1; }
+	if test "FAIL$V_INCLUDE_LIBTCL" = "FAIL" ; then
+		NS_PACKAGE_libTcl_COMPLETE=false
+		echo "$ac_t""no" 1>&6
+	else
+
+				  ac_tr_hdr=HAVE_`echo Tcl.h | sed 'y%abcdefghijklmnopqrstuvwxyz./-%ABCDEFGHIJKLMNOPQRSTUVWXYZ___%'`
+		                cat >> confdefs.h <<EOF
+#define $ac_tr_hdr 1
+EOF
+
+
+		V_INCLUDES="$V_INCLUDE_LIBTCL $V_INCLUDES"
+		V_DEFINES="-D$ac_tr_hdr $V_DEFINES"
+
+		NS_PACKAGE_libTcl_PARTIAL=true
+
+		echo "$ac_t""$V_INCLUDE_LIBTCL" 1>&6
 	fi
 fi
 
+
+echo $ac_n "checking for libTcl$LIBTCL_VERS""... $ac_c" 1>&6
+echo "configure:2187: checking for libTcl$LIBTCL_VERS" >&5
+if test "x$d" = "xno"; then
+	: disable library
+	V_LIB_LIBTCL=FAIL
+	NS_PACKAGE_libTcl_COMPLETE=false
+	echo "$ac_t""no" 1>&6
+
+else
+	places="$LIBTCL_LIB_PLACES"
+	if test "x$d" != "x" -a "x$d" != xyes; then
+		if test ! -d $d; then
+			{ echo "configure: error: $d is not a directory" 1>&2; exit 1; }
+		fi
+		places="$LIBTCL_LIB_PLACES_D"
+	fi
+
+	V_LIB_LIBTCL=""
+		full_lib_name="Tcl$LIBTCL_VERS"
+		simple_lib_name=`echo $full_lib_name | sed -e 's/\.//'`
+		simpler_lib_name=`echo $simple_lib_name | sed -e 'y/0123456789/          /'`
+	double_break=false
+	for dir in $places; do
+		for file in $full_lib_name $simple_lib_name $simpler_lib_name
+		do
+			if test -r $dir/lib$file.so -o -r $dir/lib$file.a; then
+				V_LIB_LIBTCL="-L$dir -l$file"
+				break
+			fi
+		done
+		if $double_break; then
+			break
+		fi
+	done
+	if test "FAIL$V_LIB_LIBTCL" = "FAIL" ; then
+		NS_PACKAGE_libTcl_COMPLETE=false
+		echo "$ac_t""no" 1>&6
+	else
+		if test "$solaris"; then
+			V_LIB_LIBTCL="-R$dir $V_LIB_LIBTCL"
+		fi
+
+				ac_tr_lib=HAVE_LIB`echo Tcl$LIBTCL_VERS | sed -e 's/[^a-zA-Z0-9_]/_/g' \
+		    -e 'y/abcdefghijklmnopqrstuvwxyz/ABCDEFGHIJKLMNOPQRSTUVWXYZ/'`
+				cat >> confdefs.h <<EOF
+#define $ac_tr_lib 1
+EOF
+
+
+				V_LIBS="$V_LIB_LIBTCL $V_LIBS"
+		V_DEFINES="-D$ac_tr_lib $V_DEFINES"
+
+		NS_PACKAGE_libTcl_PARTIAL=true
+
+		echo "$ac_t""$V_LIB_LIBTCL" 1>&6
+	fi
+fi
+
+
+echo $ac_n "checking for tcl2c++""... $ac_c" 1>&6
+echo "configure:2246: checking for tcl2c++" >&5
+if test "x$d" = "xno"; then
+	: disable header
+	V_TCL2CPP_DIR=FAIL
+	NS_PACKAGE_libTcl_COMPLETE=false
+	echo "$ac_t""no" 1>&6
+
+else
+	places="$LIBTCL_PROG_PLACES"
+	if test "x$d" != "x" -a "x$d" != xyes; then
+		if test ! -d $d; then
+			{ echo "configure: error: $d is not a directory" 1>&2; exit 1; }
+		fi
+		places="$LIBTCL_PROG_PLACES_D"
+	fi
+
+	V_TCL2CPP_DIR=""
+	for dir in $places; do
+		if test -r $dir/tcl2c++; then
+			V_TCL2CPP_DIR="$dir"
+			break
+		fi
+	done
+	if test "FAIL$V_TCL2CPP_DIR" = "FAIL" ; then
+		NS_PACKAGE_libTcl_COMPLETE=false
+		echo "$ac_t""no" 1>&6
+	else
+
+		NS_PACKAGE_libTcl_PARTIAL=true
+
+		echo "$ac_t""$V_TCL2CPP_DIR" 1>&6
+	fi
+fi
+
+
+V_TCL2CPP=$V_TCL2CPP_DIR/tcl2c++
+
+
+
+NS_PACKAGE_libTcl_VALID=false
+if $NS_PACKAGE_libTcl_PARTIAL; then
+	if $NS_PACKAGE_libTcl_COMPLETE; then
+		: All components of libTcl found.
+		NS_PACKAGE_libTcl_VALID=true
+	else
+		{ echo "configure: error: Installation of libTcl seems incomplete.
+Please correct the problem or re-run with --with-libTcl=no." 1>&2; exit 1; }
+	fi
+fi
+if test "xyes" = xyes; then
+	if $NS_PACKAGE_libTcl_VALID; then
+		:
+	else
+		{ echo "configure: error: libTcl is required but could not be completely found." 1>&2; exit 1; }
+	fi
+fi
+
+
+
+
+V_INCLUDE_BTCL=$V_INCLUDE_LIBTCL
+V_LIB_BTCL=$V_LIB_LIBTCL
 
 
 
@@ -2413,12 +2428,12 @@ xincdirs="\
 echo "checking for X11 header files"
 if test "$x_includes" = NONE ; then
 	cat > conftest.$ac_ext <<EOF
-#line 2417 "configure"
+#line 2432 "configure"
 #include "confdefs.h"
 #include <X11/Intrinsic.h>
 EOF
 ac_try="$ac_cpp conftest.$ac_ext >/dev/null 2>conftest.out"
-{ (eval echo configure:2422: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
+{ (eval echo configure:2437: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
 ac_err=`grep -v '^ *+' conftest.out`
 if test -z "$ac_err"; then
   rm -rf conftest*
@@ -2452,7 +2467,7 @@ fi
 echo "checking for X11 library archive"
 if test "$x_libraries" = NONE ; then
 	echo $ac_n "checking for XOpenDisplay in -lX11""... $ac_c" 1>&6
-echo "configure:2456: checking for XOpenDisplay in -lX11" >&5
+echo "configure:2471: checking for XOpenDisplay in -lX11" >&5
 ac_lib_var=`echo X11'_'XOpenDisplay | sed 'y%./+-%__p_%'`
 if eval "test \"`echo '$''{'ac_cv_lib_$ac_lib_var'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
@@ -2460,7 +2475,7 @@ else
   ac_save_LIBS="$LIBS"
 LIBS="-lX11  $LIBS"
 cat > conftest.$ac_ext <<EOF
-#line 2464 "configure"
+#line 2479 "configure"
 #include "confdefs.h"
 /* Override any gcc2 internal prototype to avoid an error.  */
 /* We use char because int might match the return type of a gcc2
@@ -2471,7 +2486,7 @@ int main() {
 XOpenDisplay()
 ; return 0; }
 EOF
-if { (eval echo configure:2475: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest; then
+if { (eval echo configure:2490: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest; then
   rm -rf conftest*
   eval "ac_cv_lib_$ac_lib_var=yes"
 else
@@ -2511,7 +2526,7 @@ V_LIB_X11=-lX11
 if test -n "$V_SHM" ; then
 	if test -z "$x_libraries" ; then
 		echo $ac_n "checking for XShmAttach in -lXext""... $ac_c" 1>&6
-echo "configure:2515: checking for XShmAttach in -lXext" >&5
+echo "configure:2530: checking for XShmAttach in -lXext" >&5
 ac_lib_var=`echo Xext'_'XShmAttach | sed 'y%./+-%__p_%'`
 if eval "test \"`echo '$''{'ac_cv_lib_$ac_lib_var'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
@@ -2519,7 +2534,7 @@ else
   ac_save_LIBS="$LIBS"
 LIBS="-lXext -lX11 $LIBS"
 cat > conftest.$ac_ext <<EOF
-#line 2523 "configure"
+#line 2538 "configure"
 #include "confdefs.h"
 /* Override any gcc2 internal prototype to avoid an error.  */
 /* We use char because int might match the return type of a gcc2
@@ -2530,7 +2545,7 @@ int main() {
 XShmAttach()
 ; return 0; }
 EOF
-if { (eval echo configure:2534: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest; then
+if { (eval echo configure:2549: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest; then
   rm -rf conftest*
   eval "ac_cv_lib_$ac_lib_var=yes"
 else
@@ -2601,7 +2616,7 @@ NS_PACKAGE_tcldebug_COMPLETE=true
 
 
 echo $ac_n "checking for libtcldbg""... $ac_c" 1>&6
-echo "configure:2605: checking for libtcldbg" >&5
+echo "configure:2620: checking for libtcldbg" >&5
 if test "x$d" = "xno"; then
 	: disable library
 	V_LIB_TCLDEBUG=FAIL
@@ -2700,7 +2715,7 @@ DMALLOC_PATH="$PWD/../dmalloc \
 
 if test "x$d" = xUNDEF; then
 	echo $ac_n "checking dmalloc""... $ac_c" 1>&6
-echo "configure:2704: checking dmalloc" >&5
+echo "configure:2719: checking dmalloc" >&5
 	echo "$ac_t""not requested with --with-dmalloc" 1>&6
 else
 	
@@ -2709,7 +2724,7 @@ NS_PACKAGE_dmalloc_COMPLETE=true
 
 	
 echo $ac_n "checking for libdmalloc""... $ac_c" 1>&6
-echo "configure:2713: checking for libdmalloc" >&5
+echo "configure:2728: checking for libdmalloc" >&5
 if test "x$d" = "xno"; then
 	: disable library
 	dmalloc=FAIL
@@ -2768,7 +2783,7 @@ fi
 
 	
 echo $ac_n "checking for dmalloc.h""... $ac_c" 1>&6
-echo "configure:2772: checking for dmalloc.h" >&5
+echo "configure:2787: checking for dmalloc.h" >&5
 if test "x$d" = "xno"; then
 	: disable header
 	dmalloc=FAIL
@@ -2813,7 +2828,7 @@ fi
 
 	
 echo $ac_n "checking for return.h""... $ac_c" 1>&6
-echo "configure:2817: checking for return.h" >&5
+echo "configure:2832: checking for return.h" >&5
 if test "x$d" = "xno"; then
 	: disable header
 	dmalloc=FAIL
@@ -2944,7 +2959,7 @@ if test ! -z "$V_NEED_DL" ; then
 		;;
 	*-*-linux*)
 		echo $ac_n "checking for dlopen in -ldl""... $ac_c" 1>&6
-echo "configure:2948: checking for dlopen in -ldl" >&5
+echo "configure:2963: checking for dlopen in -ldl" >&5
 ac_lib_var=`echo dl'_'dlopen | sed 'y%./+-%__p_%'`
 if eval "test \"`echo '$''{'ac_cv_lib_$ac_lib_var'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
@@ -2952,7 +2967,7 @@ else
   ac_save_LIBS="$LIBS"
 LIBS="-ldl  $LIBS"
 cat > conftest.$ac_ext <<EOF
-#line 2956 "configure"
+#line 2971 "configure"
 #include "confdefs.h"
 /* Override any gcc2 internal prototype to avoid an error.  */
 /* We use char because int might match the return type of a gcc2
@@ -2963,7 +2978,7 @@ int main() {
 dlopen()
 ; return 0; }
 EOF
-if { (eval echo configure:2967: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest; then
+if { (eval echo configure:2982: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest; then
   rm -rf conftest*
   eval "ac_cv_lib_$ac_lib_var=yes"
 else
@@ -2992,7 +3007,7 @@ fi
 			;;
 		*)
 			echo $ac_n "checking for main in -l$V_LIB_DL""... $ac_c" 1>&6
-echo "configure:2996: checking for main in -l$V_LIB_DL" >&5
+echo "configure:3011: checking for main in -l$V_LIB_DL" >&5
 ac_lib_var=`echo $V_LIB_DL'_'main | sed 'y%./+-%__p_%'`
 if eval "test \"`echo '$''{'ac_cv_lib_$ac_lib_var'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
@@ -3000,14 +3015,14 @@ else
   ac_save_LIBS="$LIBS"
 LIBS="-l$V_LIB_DL $V_STATIC $LIBS"
 cat > conftest.$ac_ext <<EOF
-#line 3004 "configure"
+#line 3019 "configure"
 #include "confdefs.h"
 
 int main() {
 main()
 ; return 0; }
 EOF
-if { (eval echo configure:3011: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest; then
+if { (eval echo configure:3026: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest; then
   rm -rf conftest*
   eval "ac_cv_lib_$ac_lib_var=yes"
 else
@@ -3104,7 +3119,7 @@ V_TAR_TARGET=$target_os
 # SVR4 /usr/ucb/install, which tries to use the nonexistent group "staff"
 # ./install, which can be erroneously created by make from ./install.sh.
 echo $ac_n "checking for a BSD compatible install""... $ac_c" 1>&6
-echo "configure:3108: checking for a BSD compatible install" >&5
+echo "configure:3123: checking for a BSD compatible install" >&5
 if test -z "$INSTALL"; then
 if eval "test \"`echo '$''{'ac_cv_path_install'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
@@ -3320,9 +3335,9 @@ s%@V_OBJ_MPLUG@%$V_OBJ_MPLUG%g
 s%@V_LIBRARY_TCL@%$V_LIBRARY_TCL%g
 s%@V_TKDOSNAMES@%$V_TKDOSNAMES%g
 s%@V_LIBRARY_TK@%$V_LIBRARY_TK%g
+s%@V_TCL2CPP@%$V_TCL2CPP%g
 s%@V_INCLUDE_BTCL@%$V_INCLUDE_BTCL%g
 s%@V_LIB_BTCL@%$V_LIB_BTCL%g
-s%@V_TCL2CPP@%$V_TCL2CPP%g
 s%@V_INCLUDE_X11@%$V_INCLUDE_X11%g
 s%@V_LIB_X11@%$V_LIB_X11%g
 s%@V_INCLUDES@%$V_INCLUDES%g
