Split validate into portable and non-portable tests

diff --git a/validate b/validate
--- a/validate
+++ b/validate
@@ -19,7 +19,7 @@
 # WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED WARRANTIES OF
 # MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 #
-# $Header: /home/smtatapudi/Thesis/nsnam/nsnam/ns-2/validate,v 1.145 2006/02/02 18:19:44 mweigle Exp $
+# $Header: /home/smtatapudi/Thesis/nsnam/nsnam/ns-2/validate,v 1.146 2007/08/08 04:19:46 tom_henderson Exp $
 
 try () {
         for excluding in $cygwin_exclude; do
@@ -60,21 +60,21 @@ echo "(Validation can take 1-30 hours to run.)"
 
 cd tcl/test
 
+# 
+# First run portable tests
+#
 for i in \
 simple tcp testReno newreno sack tcpOptions tcpReset \
 simple-full full testReno-full testReno-bayfull sack-full \
 tcp-init-win tcpVariants LimTransmit aimd greis rfc793edu rfc2581 rbp \
-sctp \
-tcpHighspeed frto \
-friendly srm realaudio \
-ecn ecn-ack ecn-full quickstart \
-diffusion3 smac smac-multihop \
-manual-routing hier-routing algo-routing lan mcast vc session mixmode \
+sctp  tcpHighspeed frto  friendly realaudio \
+ecn ecn-ack ecn-full quickstart diffusion3 smac \
+manual-routing lan \
 red adaptive-red red-pd rio vq rem gk pi cbq schedule rr monitor jobs \
-intserv diffserv webcache mcache webtraf \
-simultaneous mip links plm linkstate mpls oddBehaviors \
-wireless-shadowing wireless-lan-aodv wireless-tdma wireless-gridkeeper \
-wireless-diffusion wireless-lan-newnode satellite WLtutorial \
+intserv diffserv webtraf \
+mip links linkstate mpls oddBehaviors \
+wireless-shadowing wireless-lan-aodv wireless-gridkeeper \
+wireless-diffusion wireless-lan-newnode WLtutorial \
 source-routing \
 misc tagged-trace message rng xcp wpan \
 energy snoop \
@@ -95,19 +95,59 @@ do
 	sleep 2
 done
 
+#
+# Repeat for non-portable test set
+#
+any_portable_failed=$any_failed
+any_failed=false
+portable_failed_list=$failed_list
+failed_list=""
+
+for i in \
+srm smac-multihop hier-routing algo-routing mcast vc session mixmode \
+simultaneous webcache mcache plm wireless-tdma satellite 
+
+do
+	date
+	try ./test-all-$i
+	date
+	sleep 2
+done
+
 echo "These messages are NOT errors and can be ignored:"
 echo "    warning: using backward compatibility mode"
 echo "    This test is not implemented in backward compatibility mode"
 echo
 
+if $any_portable_failed
+then
+    	echo
+	echo "validate overall report: some portable tests failed:"
+	echo "    $portable_failed_list"
+        if $any_failed
+        then
+	    echo "some non-portable tests also failed:"
+	    echo "    $portable_failed_list"
+        fi
+	echo "to re-run a specific test, cd tcl/test; ./test-all-TEST-NAME"
+	exit 1
+fi
+        
 if $any_failed
 then
     	echo
-	echo "validate overall report: some tests failed:"
+	echo "validate overall report: all portable tests passed but"
+	echo "some non-portable tests failed:"
 	echo "    $failed_list"
 	echo "to re-run a specific test, cd tcl/test; ./test-all-TEST-NAME"
-	echo "Notice that some tests in webcache will fail on freebsd when -O is turned on."
-	echo "This is due to some event reordering, which will disappear when -g is turned on."
+        echo ""
+	echo "Note that the non-portable test list includes files that"
+        echo "are known to pass on Linux x86 machines but that are known"
+        echo "to have some portability problems to other platforms or"
+        echo "operating systems.   Failure of one of these tests does not"
+        echo "necessarily mean that one will encounter a problem in your"
+        echo "simulations, but that one must be careful of using that"
+        echo "specific model on the system on which the validate was run."
         if  [ "${test_cygwin}" = "true" ]; then
                 cmaj=` uname -r | sed -e 's/^\([0-9]*\)\.\([0-9]*\).\([0-9]*\).*/\1/'`;
                 echo $cmaj | grep -v [0-9] >/dev/null 2>&1
@@ -141,6 +181,7 @@ then
         fi;
 	exit 1
 else
+        echo ""
 	echo "validate overall report: all tests passed"
 	exit 0
 fi
