Bug fix for 2.1b7 install problem; should have --with-tcl=../tclbox --with-tk=../tkbox in otcl/tclcl/ns/nam configure lines.

diff --git a/allinone/install b/allinone/install
--- a/allinone/install
+++ b/allinone/install
@@ -18,8 +18,6 @@
 #
 
 #
-# Maintainer: Nader Salehi <salehi@isi.edu>
-# Version Date: 1999/03/16 16:10:50 PST
 #
 #
 
@@ -36,30 +34,37 @@ warn() {
 # Get current path
 CUR_PATH=`pwd`
 
-# create tcl8.0.4 and tk8.0.4 installation directory
+# create tcl8.3.2 and tk8.3.2 installation directory
 
 if [ ! -d tclbox ]
 then
 	mkdir tclbox
+else
+	rm -fr tclbox
 fi
 
 if [ ! -d tkbox ]
 then
 	mkdir tkbox
+else
+	rm -fr tkbox
 fi
 
-# install and install Tcl8.0.4
+# install and install Tcl8.3.2
 
-cd ./tcl8.0.4/unix
+cd ./tcl8.3.2/unix
+if [ -f Makefile ] ; then 
+	make distclean
+fi
 
 blame='Tcl is not part of the ns project.  Please see www.Scriptics.com
 to see if they have a fix for your platform.'
-./configure --enable-gcc --prefix="$CUR_PATH/tclbox" || die "tcl8.0.4 configuration failed! Exiting ..."
+./configure --enable-gcc --prefix="$CUR_PATH/tclbox" || die "tcl8.3.2 configuration failed! Exiting ..."
 if make 
 then 
-	make install || die "tcl8.0.4 installation failed! Exiting ..."
+	make install || die "tcl8.3.2 installation failed! Exiting ..."
 else
-	echo "tcl8.0.4 make failed! Exiting ..."
+	echo "tcl8.3.2 make failed! Exiting ..."
 	echo "For problems with Tcl/Tk see http://www.scriptics.com"
 	exit
 fi
@@ -68,16 +73,19 @@ cd ../../
 
 # compile and install tk
 
-cd ./tk8.0.4/unix
+cd ./tk8.3.2/unix
+if [ -f Makefile ] ; then
+	make distclean
+fi
 
 blame='Tk is not part of the ns project.  Please see www.Scriptics.com
 to see if they have a fix for your platform.'
-./configure --enable-gcc --prefix="$CUR_PATH/tkbox" || die "tk8.0.4 configuration failed! Exiting ..."
+./configure --enable-gcc --prefix="$CUR_PATH/tkbox" || die "tk8.3.2 configuration failed! Exiting ..."
 if make 
 then
-	make install || die "tk8.0.4 installation failed! Exiting ..."
+	make install || die "tk8.3.2 installation failed! Exiting ..."
 else
-	echo "tk8.0.4 make failed! Exiting ..."
+	echo "tk8.3.2 make failed! Exiting ..."
 	echo "For problems with Tcl/Tk see http://www.scriptics.com"
 	exit
 fi
@@ -87,41 +95,41 @@ cd ../../
 
 # do some copy for otcl
 
-cp ./tcl8.0.4/generic/*.h ./tclbox/include/ || die "cp failed"
-cp ./tk8.0.4/generic/*.h ./tkbox/include/ || die "cp failed"
+cp ./tcl8.3.2/generic/*.h ./tclbox/include/ || die "cp failed"
+cp ./tk8.3.2/generic/*.h ./tkbox/include/ || die "cp failed"
 
 # compile and install otcl
 
-cd ./otcl-1.0a5
+cd ./otcl-1.0a6
 
-blame='Please check http://www-mash.cs.berkeley.edu/ns/ns-problems.html
+blame='Please check http://www.isi.edu/nsnam/ns/ns-problems.html
 for common problems and bug fixes.'
-./configure --enable-gcc --with-tcl=../tclbox --with-tk=../tkbox || die "otcl-1.0a4 configuration failed! Exiting ..."
+./configure --with-tcl=../tclbox --with-tk=../tkbox || die "otcl-1.0a6 configuration failed! Exiting ..."
 
 if make 
 then
-	echo "otcl-1.0a5 has been installed successfully."
+	echo "otcl-1.0a6 has been installed successfully."
 else
-	echo "otcl-1.0a5 make failed! Exiting ..."
-	echo "See http://www-mash.CS.Berkeley.EDU/ns/ns-problems.html for problems"
+	echo "otcl-1.0a6 make failed! Exiting ..."
+	echo "See http://www.isi.edu/nsnam/ns/ns-problems.html for problems"
 	exit
 fi
 
 
 cd ../
 
-# compile and install tclcl-1.0b9
+# compile and install tclcl-1.0b10
 
-cd ./tclcl-1.0b9
+cd ./tclcl-1.0b10
 
-./configure --enable-gcc --with-otcl=../otcl-1.0a5 --with-tcl=../tclbox --with-tk=../tkbox  --with-tcl-ver=8.0.4 --with-tk-ver=8.0.4 || die "tclcl-1.0b9 configuration failed! Exiting ..."
+./configure --with-tcl=../tclbox --with-tk=../tkbox || die "tclcl-1.0b10 configuration failed! Exiting ..."
 
 if make
 then
-	echo "tclcl-1.0b9 has been installed successfully."
+	echo "tclcl-1.0b10 has been installed successfully."
 else
-	echo "tclcl-1.0b9 make failed! Exiting ..."
-	echo "See http://www-mash.CS.Berkeley.EDU/ns/ns-problems.html for problems"
+	echo "tclcl-1.0b10 make failed! Exiting ..."
+	echo "See http://www.isi.edu/nsnam/ns/ns-problems.html for problems"
 	exit
 fi	
 
@@ -131,7 +139,7 @@ cd ../
 #compile and install xgraph
 
 cd ./xgraph-12.1
-./configure --enable-gcc --prefix=../
+./configure --prefix=../
 if make
 then
 	echo "xgraph has been installed successfully. "
@@ -226,16 +234,15 @@ else
     echo "sgb lib not found. gt-itm & sgb2ns could not be installed. Continuing.."
 fi
 
-#compile and install ns
+# Compile and install ns. Since ns searches for tclsh in $PATH, the following is needed.
 PATH=$CUR_PATH/tclbox/bin:$CUR_PATH/tkbox/bin:$PATH
 export PATH
-#echo $PATH
 
 # John's hack
-test -f ./otcl-1.0a5/libotcl.a && rm ./otcl-1.0a5/libotcl.so
+test -f ./otcl-1.0a6/libotcl.a && rm ./otcl-1.0a6/libotcl.so
 
-cd ./ns-2.1b6
-./configure --enable-gcc --with-otcl=../otcl-1.0a5 --with-tclcl=../tclcl-1.0b9 --with-tcl=../tclbox --with-tk=../tkbox --disable-static || die "Ns configuration failed! Exiting ..."
+cd ./ns-2.1b7
+./configure --with-tcl=../tclbox --with-tk=../tkbox || die "Ns configuration failed! Exiting ..."
 
 if make
 then
@@ -269,16 +276,16 @@ cd ../
 
 #compile and install nam
 
-cd ./nam-1.0a8
+cd ./nam-1.0a9
 
-./configure --enable-gcc --with-otcl=../otcl-1.0a5 --with-tclcl=../tclcl-1.0b9 --with-tcl=../tclbox --with-tk=../tkbox --with-tcldebug=no --disable-static || die "Nam configuration failed! Exiting ..."
+./configure --with-tcl=../tclbox --with-tk=../tkbox || die "Nam configuration failed! Exiting ..."
 
 if make
 then 
     echo "Nam has been installed successfully."
 else
     echo "Nam make failed! Continue ..."
-    echo "See http://www-mash.CS.Berkeley.EDU/ns/ns-problems.html for problems"
+    echo "See http://www.isi.edu/nsnam/ns-problems.html for problems"
 fi
 
 cd ../
@@ -292,11 +299,11 @@ fi
 
 cd bin
 
-ln -s $CUR_PATH/ns-2.1b6/ns ns
+ln -s $CUR_PATH/ns-2.1b7/ns ns
 
-if test -x $CUR_PATH/nam-1.0a8/nam
+if test -x $CUR_PATH/nam-1.0a9/nam
 then
-    ln -s $CUR_PATH/nam-1.0a8/nam nam
+    ln -s $CUR_PATH/nam-1.0a9/nam nam
 else
     echo "Please compile your nam separately."
 fi
@@ -322,15 +329,15 @@ fi
 
 echo "Ns-allinone package has been installed successfully."
 echo "Here are the installation places:"
-echo "ns:	$CUR_PATH/ns-2.1b6/ns"
-echo "otcl:	$CUR_PATH/otcl-1.0a5"
-echo "tclcl:	$CUR_PATH/tclcl-1.0b9"
-echo "tcl8.0.4:	$CUR_PATH/tclbox"
-echo "tk8.0.4:	$CUR_PATH/tkbox"
+echo "ns:	$CUR_PATH/ns-2.1b7/ns"
+echo "otcl:	$CUR_PATH/otcl-1.0a6"
+echo "tclcl:	$CUR_PATH/tclcl-1.0b10"
+echo "tcl8.3.2:	$CUR_PATH/tclbox"
+echo "tk8.3.2:	$CUR_PATH/tkbox"
 
-if [ -x $CUR_PATH/nam-1.0a8/nam ]
+if [ -x $CUR_PATH/nam-1.0a9/nam ]
 then
-echo "nam:	$CUR_PATH/nam-1.0a8/nam"
+echo "nam:	$CUR_PATH/nam-1.0a9/nam"
 fi
 
 if [ -x $CUR_PATH/xgraph-12.1/xgraph ]
@@ -343,15 +350,18 @@ echo "gt-itm:   $CUR_PATH/itm, edriver, sgb2alt, sgb2ns, sgb2comns, sgb2hierns"
 fi
 
 echo ""
-echo "You can delete $CUR_PATH/tcl8.0.4 and $CUR_PATH/tk8.0.4 if "
+echo "You can delete $CUR_PATH/tcl8.3.2 and $CUR_PATH/tk8.3.2 if "
 echo "you want save your disk space"
 
 echo "-----------------------------------------------------"
 echo "Please put $CUR_PATH/bin into your PATH environment."
-echo "On some systems you many need to put $CUR_PATH/otcl-1.0a5 into your LD_LIBRARY_PATH environment!"
+echo ""
+echo "You MUST put $CUR_PATH/otcl-1.0a6, $CUR_PATH/tclbox/lib, $CUR_PATH/tkbox/lib"
+echo "into your LD_LIBRARY_PATH environment variable. If it complains about X libraries,"
+echo "add path to your X libraries into LD_LIBRARY_PATH."
 echo ""
 echo "You can run the ns validation suite with"
-echo "cd ns-2.1b6; ./validate"
+echo "cd ns-2.1b7; ./validate"
 
 exit 0
 
