updates for ns-2.35-RC2

diff --git a/allinone/install b/allinone/install
--- a/allinone/install
+++ b/allinone/install
@@ -16,7 +16,7 @@
 # WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED WARRANTIES OF
 # MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 #
-# $Header: /home/smtatapudi/Thesis/nsnam/nsnam/ns-2/allinone/install,v 1.34 2010/02/24 04:22:52 tom_henderson Exp $
+# $Header: /home/smtatapudi/Thesis/nsnam/nsnam/ns-2/allinone/install,v 1.35 2010/03/08 04:47:18 tom_henderson Exp $
 
 die() {
 	echo "$@"  1>&2
@@ -64,7 +64,7 @@ test_packages() {
 }
 
 cygwin_tests() {
-        echo -n "Checking Cygwin version is >= 1.3.12... "
+        echo -n "Checking Cygwin version is >= 1.7.1... "
         cmaj=` uname -r | sed -e 's/^\([0-9]*\)\.\([0-9]*\).\([0-9]*\).*/\1/'`;
         echo $cmaj | grep -v [0-9] >/dev/null 2>&1
         if [ "$?" -eq "0" ]; then
@@ -81,13 +81,13 @@ cygwin_tests() {
                 cpat=0;
         fi;
         echo -n "$cmaj.$cmin.$cpat ";
-        if ([ "$cmaj" -gt "1" ]) || ([ "$cmaj" -eq "1" ] && [ $cmin -gt "3" ]) || ([ "$cmaj" -eq 1 ] && [ $cmin -eq "3" ] && [ "$cpat" -ge "12" ]); then
+        if ([ "$cmaj" -gt "1" ]) || ([ "$cmaj" -eq "1" ] && [ $cmin -gt "7" ]) || ([ "$cmaj" -eq 1 ] && [ $cmin -eq "7" ] && [ "$cpat" -ge "1" ]); then
                 echo "(should be ok)";
         else
                 echo "(NO!)";
                 echo "";
                 echo "ns-allinone-${NSVER} has not been tested under versions of Cygwin older than";
-                echo "1.3.12. Your version ($cmaj.$cmin.$cpat) appears to be older than that. Success of";
+                echo "1.7.1. Your version ($cmaj.$cmin.$cpat) appears to be older than that. Success of";
                 echo "the install process is therefore NOT GUARANTEED.";
                 echo "";
                 cygversion="failed";
@@ -175,39 +175,18 @@ cygwin_tests() {
         fi;     
 
         echo -n "Checking for X... ";
-        cygcheck -c xorg-x11-base | grep xorg-x11-base >/dev/null 2>&1;
-        if [ "$?" -eq "0" ]; then
-                echo "X.org";
-                test_packages ${packages_xorg}
-                
-        else
-                cygcheck -c XFree86-base | grep XFree86-base >/dev/null 2>&1;
-                if [ "$?" -eq "0" ]; then
-                        echo "XFree86";
-                        test_packages ${packages_xfree}                                              
-                else 
-                        echo "None found!";
-                        
-                        echo "";
-                        echo "Neither Package xorg-x11-base nor XFree86-base is present on your system.";
-                        echo "";
-                        echo "Please install one of it using Cygwin's setup.exe";
-                        echo "before trying to install the ns-2 distribution.";
-                        test_proceed;
-                        
-                 fi;
-        fi;
+        test_packages ${packages_xorg}
     }
 
 
 # Package VERSIONs. Change these when releasing new packages
-TCLVER=8.4.18
-TKVER=8.4.18
-OTCLVER=1.13
-TCLCLVER=1.19
-NSVER=2.34
-NAMVER=1.14
-XGRAPHVER=12.1
+TCLVER=8.5.8
+TKVER=8.5.8
+OTCLVER=1.14
+TCLCLVER=1.20
+NSVER=2.35
+NAMVER=1.15
+XGRAPHVER=12.2
 ZLIBVER=1.2.3
 DEI80211MRVER=1.1.4
 
@@ -225,9 +204,8 @@ if  [ `uname` = "Darwin" ]; then
 fi
 
 # A Cygwin install requires these packages:
-packages_base="gcc gcc-g++ gawk tar gzip make patch perl w32api"
-packages_xfree="XFree86-bin XFree86-prog XFree86-lib XFree86-etc"
-packages_xorg="xorg-x11-bin xorg-x11-bin-dlls xorg-x11-devel xorg-x11-libs-data xorg-x11-etc"
+packages_base="gcc4 gcc4-g++ gawk tar gzip make patch perl w32api"
+packages_xorg="xorg-server xinit libX11-devel"
 
 # Check if we are using Cygwin, and if so, if it is a good install
 # Most Cygwin fixes in the tree and this part of the install script were 
@@ -434,8 +412,9 @@ if make
 then 
 	echo "tcl$TCLVER make succeeded."
 	make install || die "tcl$TCLVER installation failed."
+	make install-private-headers || die "tcl$TCLVER installation failed."
 	echo "tcl$TCLVER installation succeeded."
-	cp ../generic/*.h ../../include
+	#cp ../generic/*.h ../../include
 else
 	echo "tcl$TCLVER make failed! Exiting ..."
 	echo "For problems with Tcl/Tk see http://www.scriptics.com"
@@ -458,11 +437,12 @@ fi
 blame='Tk is not part of the ns project.  Please see www.Scriptics.com
 to see if they have a fix for your platform.'
 autoconf
-./configure --enable-gcc --disable-shared --prefix=$CUR_PATH || die "tk$TKVER configuration failed! Exiting ..."
+./configure --enable-gcc --disable-shared --disable-xft --disable-xss --prefix=$CUR_PATH || die "tk$TKVER configuration failed! Exiting ..."
 if make 
 then
 	echo "tk$TKVER build succeeded."
 	make install || die "tk$TKVER installation failed."
+	make install-private-headers || die "tcl$TCLVER installation failed."
 	echo "tk$TKVER installation succeeded."
 else
 	echo "tk$TKVER make failed! Exiting ..."
@@ -476,10 +456,14 @@ cd ../../
 # Since our configures search for tclsh in $PATH, the following 
 # is needed. This is necessary for otcl/tclcl/ns/nam
 #
-PATH=$CUR_PATH/tcl$TCLVER/unix:$CUR_PATH/tk$TKVER/unix:$PATH
-export PATH
-LD_LIBRARY_PATH=$CUR_PATH/tcl$TCLVER/unix:$CUR_PATH/tk$TKVER/unix:$LD_LIBRARY_PATH
-export LD_LIBRARY_PATH
+#PATH=$CUR_PATH/tcl$TCLVER/unix:$CUR_PATH/tk$TKVER/unix:$PATH
+#LD_LIBRARY_PATH=$CUR_PATH/tcl$TCLVER/unix:$CUR_PATH/tk$TKVER/unix:$LD_LIBRARY_PATH
+
+# However, the above library path setting has been found to be still 
+# fragile for systems that have multiple versions of Tcl/Tk installed
+# in various places, so in the below, we will force the allinone build
+# to use the tcl/tk version installed with allinone by passing the
+# --with-tcl-ver and --with-tk-ver options
 
 # Build otcl
 
@@ -492,18 +476,26 @@ cd ./otcl-$OTCLVER
 blame='Please check http://www.isi.edu/nsnam/ns/ns-problems.html
 for common problems and bug fixes.'
 if  [ "${test_cygwin}" = "true" ]; then
-        ./configure --x-libraries=/usr/X11R6/lib --x-includes=/usr/X11R6/include || die "otcl-$OTCLVER configuration failed! Exiting ...";
+        ./configure --x-libraries=/usr/X11R6/lib --x-includes=/usr/X11R6/include --with-tcl-ver=$TCLVER --with-tk-ver=$TKVER --disable-shlib || die "otcl-$OTCLVER configuration failed! Exiting ...";
+	if make 
+	then
+		echo "otcl-$OTCLVER has been installed successfully."
+	else
+		echo "otcl-$OTCLVER make failed! Exiting ..."
+		echo "See http://www.isi.edu/nsnam/ns/ns-problems.html for problems"
+		exit
+	fi
 else
-        ./configure || die "otcl-$OTCLVER configuration failed! Exiting ...";
-fi
+        ./configure --with-tcl-ver=$TCLVER --with-tk-ver=$TKVER || die "otcl-$OTCLVER configuration failed! Exiting ...";
 
-if make 
-then
-	echo "otcl-$OTCLVER has been installed successfully."
-else
-	echo "otcl-$OTCLVER make failed! Exiting ..."
-	echo "See http://www.isi.edu/nsnam/ns/ns-problems.html for problems"
-	exit
+	if make 
+	then
+		echo "otcl-$OTCLVER has been installed successfully."
+	else
+		echo "otcl-$OTCLVER make failed! Exiting ..."
+		echo "See http://www.isi.edu/nsnam/ns/ns-problems.html for problems"
+		exit
+	fi
 fi
 
 cd ..
@@ -517,9 +509,9 @@ echo "============================================================"
 cd ./tclcl-$TCLCLVER
 
 if  [ "${test_cygwin}" = "true" ]; then
-        ./configure --x-libraries=/usr/X11R6/lib --x-includes=/usr/X11R6/include || die "tclcl-$TCLCLVER configuration failed! Exiting ...";
+        ./configure --x-libraries=/usr/X11R6/lib --x-includes=/usr/X11R6/include --with-tcl-ver=$TCLVER --with-tk-ver=$TKVER || die "tclcl-$TCLCLVER configuration failed! Exiting ...";
 else
-        ./configure --with-otcl=../otcl-$OTCLVER || die "tclcl-$TCLCLVER configuration failed! Exiting ..."
+        ./configure --with-otcl=../otcl-$OTCLVER --with-tcl-ver=$TCLVER --with-tk-ver=$TKVER || die "tclcl-$TCLCLVER configuration failed! Exiting ..."
 fi
 
 if make
@@ -546,9 +538,9 @@ if [ -f Makefile ] ; then
 fi
 
 if  [ "${test_cygwin}" = "true" ]; then
-        ./configure --x-libraries=/usr/X11R6/lib --x-includes=/usr/X11R6/include || die "Ns configuration failed! Exiting ...";
+        ./configure --x-libraries=/usr/X11R6/lib --x-includes=/usr/X11R6/include --with-tcl-ver=$TCLVER --with-tk-ver=$TKVER || die "Ns configuration failed! Exiting ...";
 else
-        ./configure --with-otcl=../otcl-$OTCLVER --with-tclcl=../tclcl-$TCLCLVER || die "Ns configuration failed! Exiting ...";
+        ./configure --with-otcl=../otcl-$OTCLVER --with-tclcl=../tclcl-$TCLCLVER --with-tcl-ver=$TCLVER --with-tk-ver=$TKVER || die "Ns configuration failed! Exiting ...";
 fi
 
 if make
@@ -579,9 +571,9 @@ ln -s /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundat
 fi
 
 if  [ "${test_cygwin}" = "true" ]; then
-        ./configure --x-libraries=/usr/X11R6/lib --x-includes=/usr/X11R6/include --with-tclcl=$CUR_PATH/tclcl-$TCLCLVER  || die "Nam configuration failed! Exiting ...";
+        ./configure --x-libraries=/usr/X11R6/lib --x-includes=/usr/X11R6/include --with-tclcl=$CUR_PATH/tclcl-$TCLCLVER  --with-tcl-ver=$TCLVER --with-tk-ver=$TKVER || die "Nam configuration failed! Exiting ...";
 else
-        ./configure --with-otcl=../otcl-$OTCLVER --with-tclcl=../tclcl-$TCLCLVER || die "Nam configuration failed! Exiting ...";
+        ./configure --with-otcl=../otcl-$OTCLVER --with-tclcl=../tclcl-$TCLCLVER --with-tcl-ver=$TCLVER --with-tk-ver=$TKVER || die "Nam configuration failed! Exiting ...";
 fi
 
 if make
@@ -590,8 +582,8 @@ then
 elif  [ "${test_darwin}" = "true" ]; then
     # XXX workaround for OS X nam Tcl/Tk problems
     echo "Nam make failed! Trying to relink..."
-    echo "g++ -o nam tkcompat.o tkUnixInit.o xwd.o netview.o netmodel.o edge.o packet.o node.o main.o trace.o queue.o drop.o animation.o agent.o feature.o route.o transform.o paint.o state.o monitor.o anetmodel.o random.o rng.o view.o graphview.o netgraph.o tracehook.o lan.o psview.o group.o editview.o tag.o address.o animator.o wnetmodel.o nam_stream.o enetmodel.o testview.o parser.o trafficsource.o lossmodel.o queuehandle.o gen/version.o gen/nam_tcl.o  ../tcl8.4.18/unix/libtcl8.4.a ../tk8.4.18/unix/libtk8.4.a ../tcl8.4.18/unix/libtclstub8.4.a -L../tclcl-1.19 -ltclcl -L../otcl -lotcl -L/usr/lib -lz -L/usr/X11R6/lib -lXext -lX11 -lm -L. -lcorefoundation"
-    g++ -o nam tkcompat.o tkUnixInit.o xwd.o netview.o netmodel.o edge.o packet.o node.o main.o trace.o queue.o drop.o animation.o agent.o feature.o route.o transform.o paint.o state.o monitor.o anetmodel.o random.o rng.o view.o graphview.o netgraph.o tracehook.o lan.o psview.o group.o editview.o tag.o address.o animator.o wnetmodel.o nam_stream.o enetmodel.o testview.o parser.o trafficsource.o lossmodel.o queuehandle.o gen/version.o gen/nam_tcl.o  ../tcl8.4.18/unix/libtcl8.4.a ../tk8.4.18/unix/libtk8.4.a ../tcl8.4.18/unix/libtclstub8.4.a -L../tclcl-1.19 -ltclcl -L../otcl -lotcl -L/usr/lib -lz -L/usr/X11R6/lib -lXext -lX11 -lm -L. -lcorefoundation
+    echo "g++ -o nam tkcompat.o tkUnixInit.o xwd.o netview.o netmodel.o edge.o packet.o node.o main.o trace.o queue.o drop.o animation.o agent.o feature.o route.o transform.o paint.o state.o monitor.o anetmodel.o random.o rng.o view.o graphview.o netgraph.o tracehook.o lan.o psview.o group.o editview.o tag.o address.o animator.o wnetmodel.o nam_stream.o enetmodel.o testview.o parser.o trafficsource.o lossmodel.o queuehandle.o gen/version.o gen/nam_tcl.o  ../tcl8.5.8/unix/libtcl8.5.a ../tk8.5.8/unix/libtk8.5.a ../tcl8.5.8/unix/libtclstub8.5.a -L../tclcl-1.20 -ltclcl -L../otcl -lotcl -L/usr/lib -lz -L/usr/X11R6/lib -lXext -lX11 -lm -L. -lcorefoundation"
+    g++ -o nam tkcompat.o tkUnixInit.o xwd.o netview.o netmodel.o edge.o packet.o node.o main.o trace.o queue.o drop.o animation.o agent.o feature.o route.o transform.o paint.o state.o monitor.o anetmodel.o random.o rng.o view.o graphview.o netgraph.o tracehook.o lan.o psview.o group.o editview.o tag.o address.o animator.o wnetmodel.o nam_stream.o enetmodel.o testview.o parser.o trafficsource.o lossmodel.o queuehandle.o gen/version.o gen/nam_tcl.o  ../tcl8.5.8/unix/libtcl8.5.a ../tk8.5.8/unix/libtk8.5.a ../tcl8.5.8/unix/libtclstub8.5.a -L../tclcl-1.20 -ltclcl -L../otcl -lotcl -L/usr/lib -lz -L/usr/X11R6/lib -lXext -lX11 -lm -L. -lcorefoundation
     if [ -e nam ]; then
         echo "Nam relinking succeeded; nam has been installed successfully."
     else
